// ============================================================================
// HCPU Gowin FPGA Wrapper — hcpu_gowin_top.v
// Target: Tang Nano 9K (GW1NR-LV9QN88PC6/I5)
// (c) 2026 HMCL
// ============================================================================
//
// Board resources:
//   - 27 MHz onboard oscillator
//   - 6 LEDs (active low)
//   - 2 buttons (active low)
//   - UART via USB-C
//
// ── On the clock ────────────────────────────────────────────────────────────
//
// This wrapper used to instantiate a PLL whose body was `assign clkout = clkin`
// with a comment calling it a placeholder, while passing CLK_HZ = 50_000_000
// down to hcpu_top. The core therefore sized CLKS_PER_BIT for 50 MHz and ran at
// 27, putting the UART at 62,212 baud instead of 115,200 — 46% off, far outside
// the 2–3% a receiver tolerates. Nothing would have come out of the serial port
// but noise, and nothing in the design said so.
//
// The frequency is now derived from USE_PLL rather than written down twice, so
// the two cannot disagree again.
//
// USE_PLL = 0 (default) runs straight off the 27 MHz oscillator. Correct,
// verifiable in simulation, and needs no vendor IP.
//
// USE_PLL = 1 expects a Gowin rPLL generated by the IDE's IP generator. Note
// that 50 MHz is not a good target from a 27 MHz reference: 50/27 is already in
// lowest terms, so IDIV+1 must be 27 and the phase detector would run at 1 MHz,
// below the range Gowin's rPLL specifies. 54 MHz — a straight doubling — keeps
// the detector at 27 MHz and is what SYS_HZ assumes. Check the generated
// parameters against the datasheet before trusting the number.
//

`include "hcpu_pkg.vh"

module hcpu_gowin_top #(
    parameter USE_PLL = 0,           // 0: run at 27 MHz; 1: use the rPLL
    parameter BAUD    = 115200
) (
    input  wire        clk_27m,      // 27 MHz onboard oscillator
    input  wire        btn_rst_n,    // Button S2 — active low reset
    output wire        uart_txd,     // UART TX → USB bridge
    output wire [5:0]  led           // 6 LEDs — active low
);

    localparam OSC_HZ = 27_000_000;
    // Single source of truth for the system frequency. hcpu_top sizes the UART
    // divider from this, so it must describe the clock that actually arrives.
    localparam SYS_HZ = (USE_PLL != 0) ? (OSC_HZ * 2) : OSC_HZ;

    wire clk_sys;
    wire pll_locked;

    generate
        if (USE_PLL != 0) begin : g_pll
            // Replace with the Gowin IDE's generated rPLL for 27 → 54 MHz.
            Gowin_rPLL u_pll (
                .clkout (clk_sys),
                .lock   (pll_locked),
                .clkin  (clk_27m)
            );
        end else begin : g_direct
            assign clk_sys    = clk_27m;
            assign pll_locked = 1'b1;
        end
    endgenerate

    // ── Reset synchronizer ──────────────────────────────────────
    reg [2:0] rst_sync;
    wire      sys_rst_n = rst_sync[2];

    always @(posedge clk_sys or negedge btn_rst_n) begin
        if (!btn_rst_n)
            rst_sync <= 3'b000;
        else
            rst_sync <= {rst_sync[1:0], pll_locked};
    end

    // ── Instruction memory ──────────────────────────────────────
    // BRAM-style registered read with clock enable, matching what
    // hcpu_fetch.v expects: address on cycle N, data on N+1, output held
    // while imem_ce is low.
    reg [`ILEN-1:0] imem [0:`CODE_DEPTH-1];
    wire [`CODE_ADDR_W-1:0] imem_addr;
    wire                    imem_ce;
    reg  [`ILEN-1:0]        imem_data_r;
    wire [`ILEN-1:0]        imem_data;

    integer i;
    initial begin
        // Unwritten words stay NOP, so a short program cannot run into
        // whatever the block RAM powers up holding.
        for (i = 0; i < `CODE_DEPTH; i = i + 1)
            imem[i] = {`OP_NOP, 24'h000000};
        $readmemh("program.hex", imem);
    end

    always @(posedge clk_sys) begin
        if (imem_ce)
            imem_data_r <= imem[imem_addr];
    end
    assign imem_data = imem_data_r;

    // ── HCPU core ───────────────────────────────────────────────
    wire halted_out, guard_led_out;

    hcpu_top #(
        .CLK_HZ  (SYS_HZ),
        .BAUD    (BAUD),
        .USE_DSP (1)                 // FPGA: use the DSP multiplier
    ) u_hcpu (
        .clk            (clk_sys),
        .rst_n          (sys_rst_n),
        .imem_addr      (imem_addr),
        .imem_ce        (imem_ce),
        .imem_data      (imem_data),
        .uart_tx        (uart_txd),
        .halted         (halted_out),
        .guard_led      (guard_led_out),
        // Debug port — unused on FPGA, tied off
        .dbg_gpr_raddr  (5'd0),
        .dbg_gpr_rdata  (),
        .dbg_flags      ()
    );

    // ── LED mapping (active low) ────────────────────────────────
    // LED[0]: GUARD flag (on = pass)
    // LED[1]: halted (on = stopped)
    // LED[2]: PLL locked
    // LED[3]: reset active
    assign led[0] = ~guard_led_out;
    assign led[1] = ~halted_out;
    assign led[2] = ~pll_locked;
    assign led[3] = ~sys_rst_n;
    assign led[4] = 1'b1;            // off
    assign led[5] = 1'b1;            // off

endmodule
