from pathlib import Path

tree = [
    "README.md",
    "LICENSE",
    "pyproject.toml",
    "setup.cfg",
    "Makefile",
    ".gitignore",
    "hm28.rom",
    "data/hm28.json",
    "data/hm28.csv",
    "data/hm28_manifest.json",
    "docs/ARCHITECTURE.md",
    "docs/HC_LANGUAGE_SPEC.md",
    "docs/HISA_SPEC.md",
    "docs/CSGI_SPEC.md",
    "docs/HC18DC_FORMAT.md",
    "docs/ORIGIN_PROTOCOL.md",
    "docs/CHANGELOG.md",
    "docs/examples/hello.hc",
    "docs/examples/five_fields.hc",
    "docs/examples/banking.hc",
    "docs/examples/iot_guard.hc",
    "docs/examples/string_analysis.hc",
    "src/hijaiyyah/__init__.py",
    "src/hijaiyyah/__main__.py",
    "src/hijaiyyah/core/__init__.py",
    "src/hijaiyyah/core/constants.py",
    "src/hijaiyyah/core/codex_entry.py",
    "src/hijaiyyah/core/master_table.py",
    "src/hijaiyyah/core/guards.py",
    "src/hijaiyyah/core/exomatrix.py",
    "src/hijaiyyah/core/rom.py",
    "src/hijaiyyah/core/exceptions.py",
    "src/hijaiyyah/algebra/__init__.py",
    "src/hijaiyyah/algebra/vectronometry.py",
    "src/hijaiyyah/algebra/differential.py",
    "src/hijaiyyah/algebra/integral.py",
    "src/hijaiyyah/algebra/geometry.py",
    "src/hijaiyyah/algebra/exomatrix_analysis.py",
    "src/hijaiyyah/language/__init__.py",
    "src/hijaiyyah/language/grammar.py",
    "src/hijaiyyah/language/tokens.py",
    "src/hijaiyyah/language/lexer.py",
    "src/hijaiyyah/language/ast_nodes.py",
    "src/hijaiyyah/language/parser.py",
    "src/hijaiyyah/language/evaluator.py",
    "src/hijaiyyah/hisa/__init__.py",
    "src/hijaiyyah/hisa/opcodes.py",
    "src/hijaiyyah/hisa/registers.py",
    "src/hijaiyyah/hisa/machine.py",
    "src/hijaiyyah/hisa/assembler.py",
    "src/hijaiyyah/hisa/compiler.py",
    "src/hijaiyyah/skeleton/__init__.py",
    "src/hijaiyyah/skeleton/skeletonizer.py",
    "src/hijaiyyah/skeleton/contractor.py",
    "src/hijaiyyah/skeleton/csgi.py",
    "src/hijaiyyah/integrity/__init__.py",
    "src/hijaiyyah/integrity/injectivity.py",
    "src/hijaiyyah/integrity/seal.py",
    "src/hijaiyyah/integrity/audit.py",
    "src/hijaiyyah/theorems/__init__.py",
    "src/hijaiyyah/theorems/mod4_gate.py",
    "src/hijaiyyah/theorems/decomposition.py",
    "src/hijaiyyah/theorems/pythagorean.py",
    "src/hijaiyyah/theorems/energy_norm.py",
    "src/hijaiyyah/theorems/test_suite.py",
    "src/hijaiyyah/crypto/__init__.py",
    "src/hijaiyyah/crypto/hashing.py",
    "src/hijaiyyah/crypto/signing.py",
    "src/hijaiyyah/crypto/guard_filter.py",
    "src/hijaiyyah/crypto/certificate.py",
    "src/hijaiyyah/net/__init__.py",
    "src/hijaiyyah/net/codec.py",
    "src/hijaiyyah/net/json_format.py",
    "src/hijaiyyah/net/server.py",
    "src/hijaiyyah/release/__init__.py",
    "src/hijaiyyah/release/synchronizer.py",
    "src/hijaiyyah/gui/__init__.py",
    "src/hijaiyyah/gui/app.py",
    "src/hijaiyyah/gui/theme.py",
    "src/hijaiyyah/gui/widgets.py",
    "src/hijaiyyah/gui/tabs/__init__.py",
    "src/hijaiyyah/gui/tabs/letter_explorer.py",
    "src/hijaiyyah/gui/tabs/master_table.py",
    "src/hijaiyyah/gui/tabs/theorems.py",
    "src/hijaiyyah/gui/tabs/string_integral.py",
    "src/hijaiyyah/gui/tabs/audit.py",
    "src/hijaiyyah/gui/tabs/five_fields.py",
    "src/hijaiyyah/gui/tabs/geometry.py",
    "src/hijaiyyah/gui/tabs/ide.py",
    "src/hijaiyyah/gui/tabs/hisa_machine.py",
    "src/hijaiyyah/gui/tabs/bytecode.py",
    "src/hijaiyyah/gui/tabs/csgi.py",
    "src/hijaiyyah/gui/tabs/export.py",
    "src/hijaiyyah/gui/tabs/release.py",
    "hcvm.py",
    "tools/rom_generator.py",
    "tools/table_verifier.py",
    "tools/codex_calculator.py",
    "tools/benchmark.py",
    "tests/__init__.py",
    "tests/conftest.py",
    "tests/test_core/__init__.py",
    "tests/test_core/test_master_table.py",
    "tests/test_core/test_codex_entry.py",
    "tests/test_core/test_guards.py",
    "tests/test_core/test_exomatrix.py",
    "tests/test_core/test_rom.py",
    "tests/test_algebra/__init__.py",
    "tests/test_algebra/test_vectronometry.py",
    "tests/test_algebra/test_differential.py",
    "tests/test_algebra/test_integral.py",
    "tests/test_algebra/test_geometry.py",
    "tests/test_algebra/test_exomatrix_analysis.py",
    "tests/test_language/__init__.py",
    "tests/test_language/test_lexer.py",
    "tests/test_language/test_parser.py",
    "tests/test_language/test_evaluator.py",
    "tests/test_hisa/__init__.py",
    "tests/test_hisa/test_opcodes.py",
    "tests/test_hisa/test_machine.py",
    "tests/test_hisa/test_compiler.py",
    "tests/test_theorems/__init__.py",
    "tests/test_theorems/test_full_suite.py",
    "tests/test_integrity/__init__.py",
    "tests/test_integrity/test_injectivity.py",
    "tests/test_integrity/test_seal.py",
    "tests/test_integration/__init__.py",
    "tests/test_integration/test_end_to_end.py",
    "tests/test_integration/test_hcvm_standalone.py",
    "release/HL-18E-v1.0/MANIFEST.json",
    "release/HL-18E-v1.0/RELEASE_NOTES.md",
    "release/HL-18E-v1.0/CERTIFICATE.json",
    "examples/hello.hc",
    "examples/five_fields_demo.hc",
    "examples/banking_integrity.hc",
    "examples/iot_guard.hc",
    "examples/string_comparison.hc"
]

for item in tree:
    p = Path(item)
    p.parent.mkdir(parents=True, exist_ok=True)
    if not p.exists():
        p.touch()

# Special for data/kfgqpc_seal/glyphs/*.png
glyph_dir = Path("data/kfgqpc_seal/glyphs")
glyph_dir.mkdir(parents=True, exist_ok=True)
for i in range(1, 29):
    glyph_path = glyph_dir / f"{i}.png"
    if not glyph_path.exists():
        glyph_path.touch()

print("Project structure scaffolded successfully!")
